services:
  php:
    image: ghcr.io/elbformat/ibexa-icon-fieldtype/php
    volumes:
      - ./:/var/www
  phpcsfixer:
    image: ghcr.io/elbformat/php-cs-fixer:edge-php8.2
    volumes:
      - ./:/code
