ibexa:
  system:
    default:
      field_templates:
        - { template: '@ElbformatIcon/icon_field.html.twig', priority: 0 }
      fielddefinition_edit_templates:
        - { template: '@ElbformatIcon/icon_field_type_definition.html.twig', priority: 0 }