services:
  Elbformat\IconBundle\FieldType\Icon\Type:
    arguments:
      $serializer: '@eZ\Publish\SPI\FieldType\ValueSerializerInterface'
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
    tags:
      - { name: ibexa.field_type, alias: icon }
      - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: icon }
      - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: icon }

  Elbformat\IconBundle\FieldType\Icon\SearchField:
    class: 'Ibexa\Core\FieldType\Unindexed'
    tags:
      - { name: ibexa.field_type.indexable, alias: icon }

  Elbformat\IconBundle\Form\Type\IconType:
    arguments:
      $iconSetManager: '@Elbformat\IconBundle\IconSet\IconSetManager'
      $twig: '@twig'
    tags:
      - { name: form.type }
  Elbformat\IconBundle\Form\Type\IconSettingsType:
    arguments:
      $iconSetManager: '@Elbformat\IconBundle\IconSet\IconSetManager'
    tags:
      - { name: form.type }

  Elbformat\IconBundle\IconSet\IconSetManager:
    arguments:
      $configs: [] # Will be set from bundle config
